# Generated by Django 2.0.5 on 2018-05-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linetypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linetype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=200)),
                ('linetype', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Sentences',
            },
        ),
        migrations.CreateModel(
            name='WordOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('color_class', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('chunk_no', models.IntegerField(default=0)),
                ('lemma', models.CharField(max_length=100)),
                ('word', models.CharField(default='', max_length=100)),
                ('pre_verb', models.CharField(max_length=100)),
                ('morph', models.CharField(max_length=100)),
                ('colspan', models.IntegerField(default=0)),
                ('wordlength', models.IntegerField(default=0)),
                ('aux_info', models.CharField(max_length=100)),
                ('isEliminated', models.BooleanField(default=False)),
                ('isSelected', models.BooleanField(default=False)),
                ('parent', models.IntegerField(default=-1)),
                ('children', models.CharField(default='', max_length=100)),
                ('relation', models.CharField(default='', max_length=100)),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotatorapp.Sentences')),
            ],
            options={
                'db_table': 'WordOptions',
            },
        ),
        migrations.CreateModel(
            name='Wordsinsentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('parent', models.IntegerField(default=0)),
                ('children', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('wordoptions', models.CharField(max_length=100)),
                ('chunkno', models.IntegerField(default=0)),
                ('sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='annotatorapp.Sentences')),
            ],
            options={
                'db_table': 'Wordsinsentence',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wordsinsentence',
            unique_together={('sentence', 'word', 'parent', 'children', 'relation', 'wordoptions')},
        ),
        migrations.AlterUniqueTogether(
            name='wordoptions',
            unique_together={('sentence', 'level', 'color_class', 'position', 'chunk_no', 'lemma', 'pre_verb', 'morph', 'colspan', 'wordlength', 'aux_info')},
        ),
    ]
