# Generated by Django 2.0.5 on 2018-06-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotatorapp', '0004_indeclinables_noun_verbs'),
        ('annotatorapp', '0003_auto_20180610_1559'),
    ]

    operations = [
    ]
