# Generated by Django 2.0.4 on 2018-06-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotatorapp', '0005_merge_20180612_1446'),
        ('annotatorapp', '0005_merge_20180612_0955'),
    ]

    operations = [
    ]
