# Generated by Django 2.0.4 on 2018-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotatorapp', '0006_merge_20180613_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exsentences',
            fields=[
                ('xsent_id', models.AutoField(primary_key=True, serialize=False)),
                ('line', models.CharField(max_length=200)),
                ('chunks', models.CharField(max_length=200)),
                ('lemmas', models.CharField(max_length=200)),
                ('morph_cng', models.CharField(max_length=200)),
            ],
        ),
    ]
