# Generated by Django 2.0.4 on 2018-06-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotatorapp', '0007_exsentences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='line_header',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
